version: "3.3"

services:
  database:
    container_name: database-python-pro
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=pythonpro
      - POSTGRES_USER=pythonpro
      - POSTGRES_DB=cursodjango
    ports:
      - 5434:5432