name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          ports: ["5432:5432"]    