
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: [ '5432:5432' ]

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Install dependencies
        run: poetry install

      - name: Copy config .env
        run: cp contrib/env-sample .env  

      - name: Test with pytest
        run:  poetry run pytest --cov='.' -v

      - name: Send report to codecov.io
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: poetry run codecov

