name: Django Application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.9

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: poetry install 

      - name: Copy config .env
        run: cp contrib/env-sample .env  

      - name: Test with pytest
        run: |
          pytest pythondjango --nomigrations
          pytest --cov=pythondjango

      - name: Send report to codecov.io
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: poetry run codecov    