
name: CI
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports: ["5432:5432"]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: [1.1.12]
      - name: Install dependencies
        run: poetry install    
      - name: Copying configurations
        run: |
          cp contrib/env-sample .env

      - name: Test with pytest
        run:  poetry run pytest --cov='.' -v

      - name: Send report to codecov.io
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
        run: poetry run codecov
    
      - name: Lint with flake8
        run: |
          poetry run flake8 .
          
      - name: Test with pytest
        run: |
          poetry run pytest